GPG stability by iterating through multiple key servers (#133)
* fixed bug in close channels with pending channels

* refactor of litecoind docker file and changed keyservers from mit to sks-keyservers

* fix typos and update litecoind to gpg2

* enabled quiet mode for wget

* switch to high availability

* add iteration of gpg keyservers in case of failure

diff --git a/docker/bitcoind/Dockerfile b/docker/bitcoind/Dockerfile
--- a/docker/bitcoind/Dockerfile
+++ b/docker/bitcoind/Dockerfile
@@ -23,7 +23,19 @@ ENV CHECKSUM_FILENAME SHA256SUMS.asc
 # Verify bitcoin installation files and install bitcoind
 RUN wget -q https://bitcoin.org/bin/bitcoin-core-${VERSION}/${FILENAME}
 RUN wget -q https://bitcoin.org/bin/bitcoin-core-${VERSION}/${CHECKSUM_FILENAME}
-RUN gpg2 --keyserver hkp://ha.pool.sks-keyservers.net --recv-keys 0x90C8019E36C2E964
+
+# We iterate through multiple keyservers to prevent docker failures in the case a
+# single gpg server fails
+RUN for KEYSERVER_NAME in ha.pool.sks-keyservers.net \
+      hkp://p80.pool.sks-keyservers.net:80 \
+      keyserver.ubuntu.com \
+      hkp://keyserver.ubuntu.com:80 \
+      pgp.mit.edu; \
+    do \
+      gpg2 --keyserver $KEYSERVER_NAME --recv-keys 0x90C8019E36C2E964 && \
+      break || echo "$KEYSERVER_NAME failed: Trying another gpg server"; \
+    done
+
 RUN gpg2 --verify ./${CHECKSUM_FILENAME}
 RUN tar xfz /${FILENAME}
 RUN mv bitcoin-${VERSION}/bin/* /usr/local/bin/
diff --git a/docker/litecoind/Dockerfile b/docker/litecoind/Dockerfile
--- a/docker/litecoind/Dockerfile
+++ b/docker/litecoind/Dockerfile
@@ -23,7 +23,19 @@ ENV CHECKSUM_FILENAME litecoin-${VERSION}-x86_64-linux-gnu.tar.gz.asc
 # Verify litecoin installation files and install litecoind
 RUN wget -q https://download.litecoin.org/litecoin-${VERSION}/linux/${FILENAME}
 RUN wget -q https://download.litecoin.org/litecoin-${VERSION}/linux/${CHECKSUM_FILENAME}
-RUN gpg2 --keyserver hkp://ha.pool.sks-keyservers.net --recv-key FE3348877809386C
+
+# We iterate through multiple keyservers to prevent docker failures in the case a
+# single gpg server fails
+RUN for KEYSERVER_NAME in ha.pool.sks-keyservers.net \
+      hkp://p80.pool.sks-keyservers.net:80 \
+      keyserver.ubuntu.com \
+      hkp://keyserver.ubuntu.com:80 \
+      pgp.mit.edu; \
+    do \
+      gpg2 --keyserver $KEYSERVER_NAME --recv-keys FE3348877809386C && \
+      break || echo "$KEYSERVER_NAME failed: Trying another gpg server"; \
+    done
+
 RUN gpg2 --verify ./${CHECKSUM_FILENAME}
 RUN tar xfz /litecoin-${VERSION}-x86_64-linux-gnu.tar.gz
 RUN mv litecoin-${VERSION}/bin/* /usr/local/bin/
